Repository YunoHost-Apps/mastodon_ynh, pull requests merged in 2019-05, with the labels that each got.

#141 Upgrade to 2.8.2
  README.md
  README_fr.md
  conf/.env.production.sample
  conf/app.src
  conf/cron
  conf/mastodon-sidekiq.service
  conf/mastodon-web.service
  manifest.json
  scripts/install
  scripts/restore
  scripts/upgrade
Labels: enhancement

#140 Example ynh
  README.md
  README_fr.md
  check_process
  conf/.env.production.sample
  conf/message
  manifest.json
  scripts/_common.sh
  scripts/backup
  scripts/change_url
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
  scripts/ynh_send_readme_to_admin__2
  scripts/ynh_systemd_action
Labels: enhancement

#143 Cleanup dependencies
  scripts/_common.sh
  scripts/install
  scripts/restore
  scripts/upgrade
Labels: enhancement

#144 example_ynh corrections
  scripts/backup
  scripts/change_url
  scripts/install
  scripts/remove
  scripts/upgrade
Labels: enhancement

#147 Fix missing ports
  scripts/upgrade
Labels: bug

#142 Upgrade
  .travis.yml
  README.md
  README_fr.md
  check_process
  conf/.env.production.sample
  conf/app.src
  conf/cron
  conf/mastodon-sidekiq.service
  conf/mastodon-web.service
  conf/message
  manifest.json
  pull_request_template.md
  scripts/_common.sh
  scripts/backup
  scripts/change_url
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
  scripts/ynh_send_readme_to_admin__2
  scripts/ynh_systemd_action
Labels: bug, enhancement

#148 switch from ynh_add_secure_repos__3 to ynh_add_extra_apt_repos__3
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
  scripts/ynh_add_extra_apt_repos__3
Labels: enhancement

#149 switch from ynh_add_secure_repos__3 to ynh_add_extra_apt_repos__3
  manifest.json
  scripts/install
  scripts/remove
  scripts/restore
  scripts/upgrade
  scripts/ynh_add_extra_apt_repos__3
Labels: enhancement

#150 update to 2.8.3
  README.md
  README_fr.md
  check_process
  conf/app.src
  manifest.json
Labels: enhancement

#151 update to 2.8.3
  README.md
  README_fr.md
  check_process
  conf/app.src
  manifest.json
Labels: enhancement

#154 fix upgrade command syntax in readme
  README.md
  README_fr.md
Labels: enhancement

#153 Testing
  README.md
  README_fr.md
  conf/app.src
  manifest.json
Labels: enhancement
